### PR TITLE
Directory source should eagerly check allowlist

### LINKED ISSUE #1286: gitleaks still scanning node_modules and dist folder even ignoring them in gitleaks.toml in docker mode
**Describe the bug**
Hello dear friends!
My name is Jan Palach. I am facing an weird issue with gitleaks in docker mode. While using it in native executable mode nothing wrong seems to happen. The problem is, while running in docker mapping the target project to scan, gitleaks tell us that it has found the config file,but it still scanning node_modules and dist folders tooking to long to finish because my node_modules is huge. 

**To Reproduce**
1 - Follow the docker mode from the documentation
2 - put the following configfile  in a path mapped path to expose to the docker image:
`title = "Gitleaks Config File"

[extend]
useDefault = true

[allowlist]
description = "global allow lists"
paths = [
    '''.gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe)$''',
    '''(go.mod|go.sum)$''',
    '''gradle.lockfile''',
    '''yarn.lock''',
    '''package-lock.json''',
    '''package.json''',
    '''pnpm-lock.yaml''',
    '''Database.refactorlog''',
    '''vendor''',
    '''.*.test.*''',
    '''.*.swagger.*''',
    '''.*.error.*''',
    '''docs''',
    '''errors''',
    '''messages''',
    '''gitleaks_findings.json''',
    '''pre-commit''',
    '''README.md''',
    '''dist''',
    '''node_modules'''
]
`
3 - Then run the docker image pointing to the config file listed above:
docker run -v project root path:/app zricethezav/gitleaks:latest detect -l debug --no-git --source /app --verbose --no-banner --redact --config=/app/devsecops-secrets-detection/.gitleaks.toml

Result:
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
2:48PM DBG using gitleaks config /app/devsecops-secrets-detection/.gitleaks.toml from `--config`
2:48PM DBG extending config with default config
**2:50PM INF scan completed in 1m51s**
2:50PM WRN leaks found: 1
Finding:     const fooAwsSecret = "REDACTED"
Secret:      REDACTED
RuleID:      aws-access-token
Entropy:     3.646439
File:       foofile
Line:        68
Fingerprint:foofile:aws-access-token:68

**Expected behavior**
It sholud run ignoring node_modules and dist paths, but it does not. Removing these paths the docker image runs the application in an expected time window.

**Basic Info (please complete the following information):**
 - OS: MacOS
 - Gitleaks Version: Latest docker image 8.18.0

I do really appreciate your attention my friends!

cc @zricethezav

### PR DESCRIPTION
**Pull request by rgmz**
### Description:
This fixes #1286.

Comparison against a directory with a decent size `node_modules` folder.

**Before**
```
6:34PM INF scan completed in 2.57s
6:34PM WRN leaks found: 35
```

**After**
```
6:35PM INF scan completed in 113ms
6:35PM WRN leaks found: 35
```

### Checklist:

* [x] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

File: cmd/detect.go [hunk 1]
```diff
@@ -62,6 +62,10 @@ func runDetect(cmd *cobra.Command, args []string) {
 
 	detector := Detector(cmd, cfg, source)
 
+	// set follow symlinks flag
+	if detector.FollowSymlinks, err = cmd.Flags().GetBool("follow-symlinks"); err != nil {
+		log.Fatal().Err(err).Msg("")
+	}
```
Comment (rgmz) [inline cmd/detect.go:68]: This was a bug, `--follow-symlinks` had no effect because `detector.FollowSymlinks` didn't get set until after.

File: cmd/directory.go [hunk 2]
```diff
@@ -45,14 +45,23 @@ func runDirectory(cmd *cobra.Command, args []string) {
 
 	detector := Detector(cmd, cfg, source)
 
+	// set follow symlinks flag
+	if detector.FollowSymlinks, err = cmd.Flags().GetBool("follow-symlinks"); err != nil {
+		log.Fatal().Err(err).Msg("")
+	}
```
Comment (rgmz) [inline cmd/directory.go:51]: Likewise, the code to set `detector.FollowSymlinks` wasn't included in this command.

File: sources/directory.go
Comment (rgmz) [inline sources/directory.go:1]: My goal was both to fix the bug and streamline the logic of this function. The previous code has several disjointed conditions; the new code (I hope) has an intuitive flow that makes the handling clear.

File: sources/directory.go [hunk 3]
```diff
@@ -30,38 +31,60 @@ func DirectoryTargets(source string, s *semgroup.Group, followSymlinks bool) (<-
...
 
 					realPath, err := filepath.EvalSymlinks(path)
 					if err != nil {
 						return err
 					}
+
 					realPathFileInfo, _ := os.Stat(realPath)
 					if realPathFileInfo.IsDir() {
-						log.Debug().Msgf("found symlinked directory: %s -> %s [skipping]", path, realPath)
+						logger.Warn().Str("target", realPath).Msg("Skipping symlinked directory")
```
Comment (rgmz) [inline sources/directory.go:56]: I think if you have `--follow-symlinks` it's noteworthy that directories won't be scanned.

File: cmd/generate/config/base/config.go [hunk 4]
```diff
@@ -75,11 +75,8 @@ func CreateGlobalConfig() config.Config {
 
 				// ----------- JavaScript files -----------
 				// Dependencies and lock files.
-				regexp.MustCompile(`(^|/)node_modules/.*?$`),
-				regexp.MustCompile(`(^|/)package-lock\.json$`),
-				regexp.MustCompile(`(^|/)yarn\.lock$`),
-				regexp.MustCompile(`(^|/)pnpm-lock\.yaml$`),
-				regexp.MustCompile(`(^|/)npm-shrinkwrap\.json$`),
+				regexp.MustCompile(`(^|/)node_modules(/.*?)?$`),
```
Comment (rgmz) [inline cmd/generate/config/base/config.go:78]: Due to how `Walk` works this needs to match no trailing `/`, otherwise it will continue to walk every directory below.
```
frontend/node_modules
```

File: sources/directory.go [hunk 5]
```diff
@@ -30,37 +31,58 @@ func DirectoryTargets(source string, s *semgroup.Group, followSymlinks bool) (<-
...
 					}
-					paths <- ScanTarget{
-						Path:    realPath,
-						Symlink: path,
+
+					scanTarget.Path = realPath
+					scanTarget.Symlink = path
+				}
+
+				// TODO: Also run this check against the resolved symlink?
```
Comment (zricethezav) [inline sources/directory.go:64]: Not sure on this one. I think let's leave it for now and if it becomes an issue we can always add it in later.

**Comment by zricethezav** [comment]
Excellent work, nice fixes.
