### PR TITLE
Use a central logger

### LINKED ISSUE #1684: Trace log output is emitted unconditionally
**Describe the bug**

When using gitleaks as a library, gitleaks emits logging information unconditionally, for example:

```
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":2.9219282,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":3.4182959,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":3.0957952,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":3.0957952,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":3.4182959,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":3.189898,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":3.3685226,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
{"level":"trace","rule-id":"generic-api-key","path":"","entropy":2.9139771,"time":"2025-01-01T21:54:46+01:00","message":"Skipping finding due to low entropy"}
```

These log messages are generated by https://github.com/gitleaks/gitleaks/blob/b69b5157a01fe4234a74a9acd186044152a80c43/detect/detect.go#L428-L432 which uses a logger created at https://github.com/gitleaks/gitleaks/blob/b69b5157a01fe4234a74a9acd186044152a80c43/detect/detect.go#L258-L265.

**To Reproduce**

Call `detect.Dectector.DetectBytes([]byte)` with some trivial content and observe that gitleaks writes log output unconditionally.

**Expected behavior**

gitleaks should only emit log output if explicitly configured to do so.

**Screenshots**

n/a

**Basic Info (please complete the following information):**
 - OS: macOS
 - Gitleaks Version: v8.22.1

**Additional context**

The log output can be suppressed by setting `github.com/rs/zerolog/log.Logger` to `zerolog.New(io.Discard)` to discard all log output written through zerolog. This disables all zerolog logging, however.

cc @zricethezav

Edit: fix link to code generating log message.

### PR DESCRIPTION
**Pull request by rgmz**
### Description:
This potentially fixes #1684.

### Checklist:

* [x] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [ ] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by rgmz** [comment]
Thoughts @twpayne @bplaxco @zricethezav?

File: logging/log.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+import (
+	"os"
+
+	"github.com/rs/zerolog"
+)
+
+// TODO: Should this be a pointer?
+// https://github.com/rs/zerolog/issues/1
+var Logger zerolog.Logger
```
Comment (twpayne) [inline logging/log.go:11]: I don't think this should be a pointer. zerolog copies loggers when creating sub-loggers, rather than using references.

**Review by twpayne — APPROVED** [review]
This looks fantastic, exactly the improvement I wanted to see :) Thank you!

File: logging/log.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+func init() {
+	// send all logs to stdout
+	Logger = zerolog.New(zerolog.ConsoleWriter{Out: os.Stderr}).
+		Level(zerolog.InfoLevel).
+		With().Timestamp().Logger()
```
Comment (rgmz) [inline logging/log.go:17]: I need to check if there are any other differences between this and the defaults from `log.Output(zerolog.ConsoleWriter{Out: os.Stderr})`.

Comment (rgmz) [reply logging/log.go:17]: It looks the same as far as I can tell. 🤷‍♂️

**Comment by zricethezav** [comment]
excellent work

**Comment by bplaxco** [comment]
@rgmz I'm a little tardy to the party but I love that it's abstracted away a bit like that. LGTM
